# Groq AI
groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.model=llama3-8b-8192

# Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# File Upload
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=562862752012-43c266omasml0vi893j142k84lrdksmb.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.provider.google.user-name-attribute=sub